version: "3.9"

services:
    app:
        build:
            context: .
            target: php_caddy
            args:
                BUILD_DEV: true
        restart: unless-stopped
        volumes:
            - ./:/srv/app
            - /srv/app/var
        ports:
            - "80:80"
#            - "443:443"
        environment:
            APP_ENV: dev
            SERVER_NAME: enmarche.localhost
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:6-alpine

    rabbitmq:
        image: rabbitmq:3-management

    node:
        build:
            target: node
#        init: true
#        working_dir: /srv
#        command: apk add --no-cache git
        volumes:
            - ./:/srv/app